name: uno-mini-app-prod

services:

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: uno-backend-prod
    restart: always
    ports:
      - "2567:2567"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 2567
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      FRONTEND_URL: ${FRONTEND_URL}

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: uno-frontend-prod
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      PORT: 3000
      VITE_COLYSEUS_URL: ${VITE_COLYSEUS_URL}

volumes:
  postgres_prod_data: